### ISSUE TITLE
Error SNR 41

### ISSUE THREAD

**Issue by aemonge** [webdesus/polymer-ide.vim#14]
Hi when trying to use polymer-ide. I'm getting the following error:

```
Error detected while processing function <SNR>41__on_stdout:
line    2:
E474: Invalid argument
line    3:
E121: Undefined variable: id
E116: Invalid arguments for function exists('s:handlers['. msg.id .']')
E15: Invalid expression: exists('s:handlers['. msg.id .']')
```

After search and replace I found it corresponds to:
```
~/.vim/plugged/polymer-ide.vim/autoload/polymer_ide.vim:17:         if exists('s:handlers['. msg.id .']')
```

I've did the NPM install inside the folder (which was a previous error I had). And I even swtiched to Plug

**Comment by webdesus** [comment]
Are you sure you use last version(version 0.4.5)? This problem alwayes airse? Or sometime?

**Comment by webdesus** [comment]
I was able to reproduce. I fix this bug soon

**Comment by aemonge** [comment]
The problem always airse...... tomorrow I can turn off all my plugins to see if there's any incompatibility.

And yes, it's the 0.4.5

**Comment by webdesus** [comment]
I had same problem by my another pc. After install node.js for my computer, problem is gone. I think you forget install node.js. See [requirements](https://github.com/webdesus/polymer-ide.vim#requirements) for more details 😊

**Comment by aemonge** [comment]
I'm using *nvm* with npx https://www.npmjs.com/package/npx. Is there an specific version of node ?
This is my `nvm list` output
```->       v8.2.1
default -> 8 (-> v8.2.1)
node -> stable (-> v8.2.1) (default)
stable -> 8.2 (-> v8.2.1) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.4 (-> N/A)
lts/boron -> v6.11.1 (-> N/A)
```

**Comment by webdesus** [comment]
I tested v6 and v8 all work fine. I don't know how work `nvm`, maybe he not register command? Try type next in terminal `node -v`

**Comment by webdesus** [comment]
I read about nvm, and yes he not working like i use nodejs. I will release patch soon and fix this problem.

**Comment by aemonge** [comment]
Thanks a lot !!!!

**Comment by webdesus** [comment]
@aemonge you found approach how register node from nvm, or make register manual?

**Comment by aemonge** [comment]
Hi!

I've executed the following `nvm alias default stable`, I can see the node version *8.2.1* when executing `:!node -v` from vim. But I'm not really sure on how to make sure it's registered on a vimScript; if you could tell me what to should a expected when running something it'll be great for me. Something like where can I a put a echo on the vimscript to make sure node is loaded.

**Comment by webdesus** [comment]
If `:!node -v` work, then vimScript too should see node😊

**Comment by aemonge** [comment]
Then I'm not sure if the error relays on node; since `:!node -v` works for me; and I'm still seeing the error.  Do you know how to disable plugins without affecting you normal VI ?  that would help me to figure out the incompatibility

**Comment by webdesus** [comment]
I usually comments all plugins. I think problem in another... I will try find time for test nvm solution.
