### ISSUE TITLE
Understanding expected behavior

### ISSUE THREAD

**Issue by srsudar** [webdesus/polymer-ide.vim#8]
I'm trying to fully appreciate what this plugin can offer, and I have a couple more basic questions. 

When I run `:w` on [this file](https://github.com/srsudar/SemCache/blob/try-webrtc/chromeapp/app/polymer-ui/elements/cache-page-list.html), the plugin complains that, among other things, `<template>` and `<dom-module>`, `<paper-spinner>`, etc are not recognized. Looking at the gifs you've included in the readme, I'm wondering if you are assuming different code structure than I'm using, or maybe I'm using an old version of Polymer or something, or maybe it is a different plugin that is causing the error. Should all the tags in that file be recognized and not generate errors with your plugin? Should I be disabling my other checkers if using this plugin?

As for completions, should the IDE-like behavior you're showing in the gifs work with [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) as the completer?

I use [vim-commentary](https://github.com/tpope/vim-commentary) for commenting. When editing Polymer `.html` files, even in script tags, it introduces comments with `<!-- -->` rather than js `//`. Is that the kind of thing this plugin could handle, even if it requires some sort of plumbing with `vim-commentary`?

**Comment by webdesus** [comment]
1) I open your files without problems.  I understand correct when you save, you see an error `not recognized` ?
2) At this moment i use standart function vim [Omni](http://vim.wikia.com/wiki/Omni_completion) completion. But i think it's good idea add support YouCompleteMe too.
3) I think it's problem vim-commentary.  I use [tcomment_vim](https://github.com/tomtom/tcomment_vim)

**Comment by webdesus** [comment]
I read about YouCompleteMe. Was surprised i think this plugin only add `typeahead-completions`, but he more powerful. But he work with omnifunc too. I'm not tested but my plugin should work with him.

**Comment by srsudar** [comment]
Here are a few more general comments/questions. Here is my [vimrc](https://github.com/srsudar/dotfiles/blob/master/vim/vimrc).

1. Yes, I see the error `not recognized`. This appears to be due to [syntastic](https://github.com/vim-syntastic/syntastic). `:SyntasticInfo` shows me several potential checkers that I have installed. `tidy` was the one active when the errors were being generated. Adding this line to my `.vimrc` removes the error: `let g:syntastic_html_checkers = []`.
2. With no checkers active but `polymer-ide.vim` active, I'm not seeing the awesome completions you demonstrate in your gifs. I instead see as shown below, kind of a general identifier based completion. Am I missing a plugin or something, maybe? Or maybe there is an added complication with `YouCompleteMe`? Removing ycm doesn't generate the completions (unless I'm using the wrong activation sequence--maybe that changes without ycm...).

<img width="290" alt="screen shot 2017-02-16 at 9 30 05 pm" src="https://cloud.githubusercontent.com/assets/6362625/23053600/a1a13df4-f48f-11e6-92c0-91e87cf24302.png">

3. Great, I'll ask there.

4. I am seeing a warning in the gutter when I have a misspelled import, as you show in the gifs. Is there a way this could be integrated with the location list, perhaps to integrate with syntastic? I'm used to seeing errors pop up in the location list, I'd love if that could be integrated somehow.

<img width="701" alt="screen shot 2017-02-16 at 9 30 36 pm" src="https://cloud.githubusercontent.com/assets/6362625/23053689/2c21561c-f490-11e6-9815-5af913dff674.png">

5. With the plugin active, my text wrapping is no longer working in markdown files. I'm not sure the wrapping is broken only in markdown files, but that's where I noticed it. I have `set wrap` in my `.vimrc`, which normally automatically wraps text when I reach a certain column. This no longer happens when the plugin is active.

**Comment by webdesus** [comment]
1. I think about how it will be possible to resolve this issue.
2. Yes problem with `YouCompleteMe`. Now I do not have the possibility to check it out. But i promise make integration with `YouCompleteMe`. #9
4. Yes i have plan make integration with `Syntastic` too. #10
5. I will test on a next week this behavior.

Thanks for you feedback it is really interesting ideas to improve polymer-ide. I will be glad if you find time for PR 😊

**Comment by srsudar** [comment]
Haha, ABSOLUTELY don't mean to just be piling things on your plate. My thinking was more that, given that this is a relatively young plugin, enumerating some of these things would be helpful. I love what this plugin offers.

**Comment by webdesus** [comment]
Yes, I understand you correctly))) All integrations will be like options. Users himself will be choose what he want switch on.😊

**Comment by webdesus** [comment]
I check wrap and he work fine for me. 
My setting wrap:
```
set wrap
set tw=80
set fo+=t
set wm=0
set linebreak
noremap :set wrap!
```

**Comment by webdesus** [comment]
About `tidy`  htacg/tidy-html5#119

I make coming soon integrations with `YouCompleteMe`. follow for  #9 

If you not have objections, i wanna close this issue.

**Comment by srsudar** [comment]
Sounds good!

**Comment by webdesus** [comment]
@srsudar i forgot to tell. Today i released integration with `Syntastic` 😊
